// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Untuk migration dan db push, gunakan DIRECT_URL jika ada
// Accelerator URL (prisma+postgres://...) tidak bisa digunakan untuk migration/db push
// Jika DIRECT_URL tidak ada, gunakan DATABASE_URL (untuk development)
const getDirectUrl = (): string => {
  try {
    // Prioritas 1: DIRECT_URL (direct database connection untuk migration)
    const directUrl = env("DIRECT_URL");
    if (directUrl) {
      return directUrl;
    }
  } catch {
    // DIRECT_URL tidak ada, lanjut ke fallback
  }
  
  // Prioritas 2: DATABASE_URL
  const databaseUrl = env("DATABASE_URL");
  
  // Jika DATABASE_URL adalah Accelerator URL, kita perlu direct URL untuk migration/db push
  if (databaseUrl.startsWith("prisma+")) {
    console.warn(
      "⚠️  WARNING: DATABASE_URL adalah Accelerator URL. " +
      "Untuk migration dan db push, set DIRECT_URL dengan direct PostgreSQL connection string. " +
      "Menggunakan Accelerator URL sebagai fallback (mungkin tidak bekerja untuk migration/db push)."
    );
  }
  
  return databaseUrl;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDirectUrl(),
  },
});
